-record(widget_test, {
	  id,
	  atom,
	  autocomplete,
	  bool, 
	  csv,
	  date,
	  datetime,
	  enum,
	  float,
	  integer,
	  multilist,
	  password,
	  string,
	  text,
	  time,
	  upload}).

-record(widget_test_types, {
	  id = {integer, [{primary_key}, 
			  {private, true}]},
	  atom = {atom, [{description, "Atom"}]},
	  autocomplete = {autocomplete, [{description, "Autocomplete"},
					 {complete, ["to","jest","test"]}]},
	  bool = {bool, [{description, "Bool"}, 
			 {always, ["man"]},
			 {options, "man:Man|animal:Woman"}]},
	  csv = {csv, [{description, "CSV"},
		       {type, string}, 
		       {delimiter, " "}]},
	  date = {date, [{description, "Date"},
			 {format, "YYYY-MM-DD"}]},
	  datetime = {datetime, [{description, "Datetime"}]},
	  enum = {enum, [{description, "Enum"},
			 {chosen, "blue"},
			 {choices, "blue:Blue|red:Red|none:I am color-blind"}]},
	  float = {float, [{description, "Float"}]},
	  integer = {integer, [{description, "Integer"}]},
	  multilist = {multilist, [{description, "Multilist"},
				   {options, "dog:Doggy|cat:Kitten|rhino:Other"},
				   {selected, ["cat", "rhino"]},
				   {html_attrs, [{multiple, "multiple"}]}]},
	  password = {password, [{description, "Password"}]},
	  string = {string, [{description, "String"},
			     {html_attrs, [{class, required}]}]},
	  text = {text, [{description, "Text"}]},
	  time = {time, [{description, "Time"}]},
	  upload = {upload, [{description, "Upload text file"},
			     {extension, ".txt"}]}}).
